[package]
name = "quic-trace-log"
version = "0.1.0"
authors = ["Alessandro Ghedini <alessandro@ghedini.me>"]
edition = "2018"
build = "src/build.rs"
publish = false

[build-dependencies]
protoc-rust = "2"

[dependencies]
regex = "1"
protobuf = "2"
humantime = "1"
